# version: '3.8' (obsolète, supprimé pour éviter les avertissements)

services:
  eureka-server:
    build: ./Eureka
    image: "ahlemalaya/ms-eureka-server:latest"
    container_name: eureka-server
    ports:
      - "8762:8761"
    networks:
      - ms-network
    restart: always



  h2-database:
    image: oscarfonts/h2
    container_name: h2-database
    ports:
      - "1522:1521"
      - "8083:8082"
    networks:
      - ms-network
    environment:
      - H2_OPTIONS=-ifNotExists -tcpAllowOthers
    volumes:
      - h2-data:/opt/h2-data
    restart: always

  gateway-service:
    build: ./Gateway
    image: "ahlemalaya/ms-gateway-service:latest"
    container_name: gateway-service
    ports:
      - "8093:8093"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - ms-network
    restart: always



  gestion-stock:
    build: ./Gestion-de-Stock
    image: "ghofraneghribi/ms-gestion-stock:latest"
    container_name: gestion-stock
    ports:
      - "8088:8088"
    depends_on:
      - eureka-server
      - h2-database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:stock_db;DB_CLOSE_DELAY=-1
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
      - SPRING_H2_CONSOLE_ENABLED=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - ms-network
    restart: on-failure



networks:
  ms-network:
    name: ms-network
    driver: bridge

volumes:

  h2-data: